project_id = "zvzunrkbcpktahpvptta"

[functions.health-assistant]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.nearby-facilities]
verify_jwt = false
